# Generated by Django 4.2.5 on 2025-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0011_alter_paymentaccount_payment_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_hash',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
