# Generated by Django 4.2.5 on 2025-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0012_user_id_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
